---
# Tasks file for myinfra.eu motd

- name: Remove default motd configuration
  block:
      - name: Create backup folder
        file:
            path: /etc/update-motd.d/backups
            state: directory
      - name: Check if we need to move files
        shell: ls /etc/update-motd.d/ --ignore=99-footer --ignore=20-update --ignore=backups
        register: move_output
      - name: Move files to backup folder
        shell: mv $(ls --ignore=99-footer --ignore=20-update --ignore=backups) /etc/update-motd.d/backups/
        args:
            chdir: /etc/update-motd.d/
        when: move_output.stdout != ""
  when: myinfra_motd_remove_default_config

- name: Restore default motd configuration from backups folder
  shell: mv /etc/update-motd.d/backups/* /etc/update-motd.d/
  when: myinfra_motd_restore_default_config and not myinfra_motd_remove_default_config

- name: Add dynamic message before motd
  template:
      src: files/20-update.j2
      dest: /etc/update-motd.d/20-update
      mode: a+x
  when: myinfra_motd_add_update | bool
  tags: ["motd", "common"]

- name: Remove dynamic message before motd
  file:
      path: /etc/update-motd.d/20-update
      state: absent
  when: not myinfra_motd_add_update | bool
  tags: ["motd", "common"]

- name: Delete /etc/motd file
  file:
      path: /etc/motd
      state: absent
  when: myinfra_motd_add_footer | bool
  tags: ["motd", "common"]

- name: Add motd
  template:
      src: file/motd.j2
      dest: /etc/motd
  when: myinfra_motd_add_update | bool
  tags: ["motd", "common"]
